"""mergekit YAML export."""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from layer_scan.scanner import ScanReport


def export_mergekit_yaml(
    report: ScanReport,
    model_path: str,
    rank: int = 1,
) -> str:
    """Export a top-k configuration as mergekit passthrough YAML.

    Args:
        report: The completed scan report.
        model_path: Model path or HuggingFace ID for the YAML output.
        rank: Which top config to export (1-indexed). Default: best.

    Returns:
        YAML string ready for ``mergekit-yaml``.

    Raises:
        ValueError: If rank is out of range or no configs available.
    """
    if not report.top_configs:
        raise ValueError("No configurations in scan report to export")

    if rank < 1 or rank > len(report.top_configs):
        raise ValueError(
            f"rank must be 1..{len(report.top_configs)}, got {rank}"
        )

    result = report.top_configs[rank - 1]
    i = result.config.i
    j = result.config.j
    total = result.config.total_layers

    lines = [
        "# Generated by layer-scan",
        f"# Config rank #{rank}: i={i}, j={j}, score={result.score:.4f}",
        f"# Baseline: {report.baseline_score:.4f}, "
        f"delta: {result.score - report.baseline_score:+.4f}",
        "",
        "merge_method: passthrough",
        "slices:",
        "  - sources:",
        f"      - model: {model_path}",
        f"        layer_range: [0, {j}]",
        "  - sources:",
        f"      - model: {model_path}",
        f"        layer_range: [{i}, {total}]",
        "",
    ]

    return "\n".join(lines)
